#!/usr/bin/env bash
#
# QA for the failures a process manager causes: a worker stopped politely,
# a worker killed, and an API restarted under a reader.
#
# Separate from run_queue_qa.py because these need docker, and because each
# one leaves the stack in a state the next has to start from.
#
# Usage:  LEGAL_AI_JWT_SECRET=... scripts/qa/run_failure_qa.sh
#
# A run takes several minutes. Do not edit this file while one is going:
# bash reads a script incrementally from disk, so an edit lands mid-run and
# the shell resumes at the wrong byte offset. Copy it and run the copy if
# you need to change it meanwhile.
set -u

BASE=${BASE:-http://localhost:8000}
PY=${PY:-.venv/bin/python}
PASS=0; FAIL=0

check() {  # check <name> <condition-as-string> <detail>
  if [ "$2" = "true" ]; then echo "  PASS  $1${3:+  -- $3}"; PASS=$((PASS+1))
  else echo "  FAIL  $1${3:+  -- $3}"; FAIL=$((FAIL+1)); fi
}

TOKEN=$($PY - <<'PYEOF'
import os, sys
sys.path.insert(0, "src")
from api.utils.tokens import issue_access_token
print(issue_access_token("qa-failure", secret=os.environ["LEGAL_AI_JWT_SECRET"]))
PYEOF
)

api() { curl -s -X "$1" "$BASE$2" -H "Authorization: Bearer $TOKEN" \
        ${3:+-H 'Content-Type: application/json' -d "$3"}; }
field() { $PY -c "import sys,json; d=json.load(sys.stdin)['data']$1; print(d)"; }

ask() {  # ask <question> -> "thread run"
  local thread run
  thread=$(api POST /threads '{}' | field "['thread_id']")
  run=$(api POST "/threads/$thread/messages" "{\"message\":\"$1\"}" | field "['run_id']")
  echo "$thread $run"
}

status() { api GET "/runs/$1" | field "['status']" 2>/dev/null || echo gone; }

ready() {  # ready <container> <since> -- block until THIS start is ready
  #
  # `since` is an RFC3339 stamp taken before the restart. Without it this
  # matches the previous session's "worker ready", which is still in the
  # log -- a container restarted seven times has seven of them -- and
  # returns instantly on a worker that has not begun loading.
  local deadline=$(( $(date +%s) + 180 ))
  while [ "$(date +%s)" -lt "$deadline" ]; do
    docker logs --since "$2" "$1" 2>&1 | grep -q "worker ready" && return 0
    sleep 3
  done
  return 1
}

now() { date -u +%Y-%m-%dT%H:%M:%SZ; }

owner() {  # owner <run> -- the worker container that claimed it
  local c
  for c in $(docker ps --format '{{.Names}}' | grep worker); do
    docker logs "$c" 2>&1 | grep -q "$1" && echo "$c" && return
  done
}

await() {  # await <run> <seconds>
  local deadline=$(( $(date +%s) + ${2:-300} )) s
  while [ "$(date +%s)" -lt "$deadline" ]; do
    s=$(status "$1")
    case "$s" in queued|running) sleep 3 ;; *) echo "$s"; return ;; esac
  done
  echo timeout
}

echo "=== 1. A worker stopped politely finishes the job in hand ==="
read -r THREAD RUN <<< "$(ask 'what is the punishment under section 138')"
sleep 10
# The worker that actually claimed it. With three running, stopping any
# other one proves nothing -- and the first version of this check did
# exactly that and reported a false failure.
WORKER=$(owner "$RUN")
if [ -z "$WORKER" ]; then
  check "found the worker running it" false "no worker logged $RUN"
  WORKER=$(docker ps --format '{{.Names}}' | grep -m1 worker)
fi
docker stop -t 240 "$WORKER" > /dev/null
S=$(status "$RUN")
check "the run survived its worker's shutdown" "$([ "$S" = done ] && echo true || echo false)" "$S"
ROLES=$(api GET "/threads/$THREAD/messages" | $PY -c "import sys,json; print([m['role'] for m in json.load(sys.stdin)['data']])")
check "and its answer was stored" "$([ "$ROLES" = "['user', 'assistant']" ] && echo true || echo false)" "$ROLES"
AT=$(now); docker start "$WORKER" > /dev/null; ready "$WORKER" "$AT"

echo
echo "=== 2. A job queued with no worker at all waits, then runs ==="
docker ps --format '{{.Names}}' | grep worker | xargs -r docker stop -t 5 > /dev/null
read -r THREAD2 RUN2 <<< "$(ask 'what is section 420 of the IPC')"
sleep 10
S=$(status "$RUN2")
check "it stays queued while nothing is serving" "$([ "$S" = queued ] && echo true || echo false)" "$S"
docker ps -a --format '{{.Names}}' | grep worker | xargs -r docker start > /dev/null
S=$(await "$RUN2" 300)
check "and runs once a worker comes back" "$([ "$S" = done ] && echo true || echo false)" "$S"

echo
echo "=== 3. A worker killed outright strands its row (the known gap) ==="
# Asserting the gap, not a fix. A row that says "running" with nothing
# behind it is what a reaper sweeping stale heartbeats will close; until
# one exists, this test is the record that we know.
read -r THREAD3 RUN3 <<< "$(ask 'is anticipatory bail available in a cheque bounce case')"
sleep 12
OWNER=$(owner "$RUN3")
if [ -z "$OWNER" ]; then
  check "found the worker running it" false "no worker logged $RUN3"
else
  docker kill "$OWNER" > /dev/null
  sleep 15
  S=$(status "$RUN3")
  check "the row is left saying running, with nothing coming" \
        "$([ "$S" = running ] && echo true || echo false)" "$S (expected until a reaper exists)"
  # Waits for "worker ready" rather than a fixed sleep. A worker loads its
  # models before claiming anything, so a 12-second sleep would find it
  # still warming -- and the assertion would pass for the wrong reason.
  AT=$(now); docker start "$OWNER" > /dev/null; ready "$OWNER" "$AT"
  sleep 8
  S=$(status "$RUN3")
  check "the row stays running until the heartbeat goes stale" \
        "$([ "$S" = running ] && echo true || echo false)" "$S"

  # And now the reaper. Aged by hand rather than by waiting out
  # STALE_AFTER_SECONDS, which is deliberately longer than a run may take.
  docker exec legal-ai-postgres psql -U legal_ai -d legal_ai -q -c \
    "UPDATE runs SET heartbeat_at = now() - interval '30 minutes' WHERE run_id = '$RUN3'" \
    > /dev/null 2>&1
  # Asserted on `attempts`, not on status. A requeued run is claimed again
  # within seconds and is therefore `running` almost immediately -- which is
  # the success path, so waiting for "not running" waits forever and reports
  # the reaper broken when it worked.
  DEADLINE=$(( $(date +%s) + 120 )); N=1
  while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    N=$(api GET "/runs/$RUN3" | field "['attempts']")
    [ "${N:-1}" -gt 1 ] && break
    sleep 5
  done
  check "a worker sweeps the abandoned row and hands it out again" \
        "$([ "${N:-1}" -gt 1 ] && echo true || echo false)" "attempts=$N"
fi

echo
echo "=== 4. The API restarts while a run is going ==="
read -r THREAD4 RUN4 <<< "$(ask 'what does section 139 presume')"
sleep 8
docker restart legal-ai-api > /dev/null
until curl -sf "$BASE/health" > /dev/null 2>&1; do sleep 2; done
S=$(await "$RUN4" 300)
check "the run finished regardless of the API restart" "$([ "$S" = done ] && echo true || echo false)" "$S"
FRAMES=$(curl -sN --max-time 30 "$BASE/runs/$RUN4/stream" -H "Authorization: Bearer $TOKEN" | grep -c "^event:")
check "and a fresh API replays the whole run" "$([ "$FRAMES" -gt 2 ] && echo true || echo false)" "$FRAMES frames"

for t in "$THREAD" "$THREAD2" "$THREAD3" "$THREAD4"; do
  [ -n "${t:-}" ] && api DELETE "/threads/$t" > /dev/null
done

echo
echo "$PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
